.bail ON
.mode columns
.headers on
.nullvalue NULL


--ELIMINA AS TABELAS SE EXISTIREM
DROP TABLE IF EXISTS ALUNO;
DROP TABLE IF EXISTS PROF;
DROP TABLE IF EXISTS CADEIRA;
DROP TABLE IF EXISTS PROVA;

--CRIA CADA UMA DAS TABELAS
CREATE TABLE ALUNO (
	nr INTEGER PRIMARY KEY,
	Nome TEXT NOT NULL
);

CREATE TABLE PROF (
	sigla TEXT PRIMARY KEY,
	Nome TEXT NOT NULL
);

CREATE TABLE CADEIRA (
	cod TEXT PRIMARY KEY,
	Design TEXT NOT NULL,
	curso TEXT NOT NULL,
	regente TEXT REFERENCES PROF(sigla)
);

CREATE TABLE PROVA (
	nr INTEGER REFERENCES ALUNO(nr),
	cod TEXT REFERENCES CADEIRA(cod),
	data DATE NOT NULL,
	nota INTEGER NOT NULL CHECK (nota >= 0 AND nota <= 20),
	CONSTRAINT PROVA_PK PRIMARY KEY (nr, cod, data)
);